AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  crud-lambda

  Sample SAM Template for crud-lambda

Parameters:
  QueueArn:
    Type: String
    Description: TestQueue's arn
  QueueUrl:
    Type: String
    Description: TestQueue's url
  DynamoDBTableStreamArn:
    Type: String
    Description: DynamoDB Table's stream arn

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      Auth:
        DefaultAuthorizer: NONE
      Cors:
        AllowMethods: "'GET,OPTIONS'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
  CRUDFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: crud-function
      CodeUri: crud-lambda/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Policies:
      - DynamoDBCrudPolicy:
          TableName: user
      Events:
        GetUsers:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /users
            Method: get
        CreateUser:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /users
            Method: post
  StreamFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: trigged-function
      CodeUri: trigged-lambda/
      Handler: app.lambda_handler
      Runtime: python3.12
      Policies:
        - AWSLambdaDynamoDBExecutionRole
      Events:
        DynamoDBStream:
          Type: DynamoDB
          Properties:
            Stream: !Ref DynamoDBTableStreamArn
            StartingPosition: LATEST
            BatchSize: 1
  InvokerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: invoker-function
      Runtime: python3.12
      Handler: app.lambda_handler
      CodeUri: invoker-lambda/
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: !GetAtt ProducerFunction.Arn
      Events:
        RandomUsersApi:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /random-users
            Method: POST
  ProducerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: producer-function
      Runtime: python3.12
      Handler: app.lambda_handler
      CodeUri: producer-lambda/
      Environment:
        Variables:
          QUEUE_URL: !Ref QueueUrl
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: "*"
  ConsumerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: consumer-lambda
      Runtime: python3.12
      Handler: app.lambda_handler
      CodeUri: consumer-lambda/
      MemorySize: 128
      Timeout: 10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: user
        - SQSPollerPolicy:
            QueueName: TestQueue.fifo
      Events:
        SqsTrigger:
          Type: SQS
          Properties:
            Queue: !Ref QueueArn
            BatchSize: 5

Outputs:
  MyApi:
    Description: API Gateway endpoint URL
      function
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/"
