AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  crud-lambda

  Sample SAM Template for crud-lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      Auth:
        DefaultAuthorizer: NONE
      Cors:
        AllowMethods: "'GET,OPTIONS'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
  CRUDFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Policies:
      - DynamoDBCrudPolicy:
          TableName: user
      Events:
        GetUsers:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /users
            Method: get
        CreateUser:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /users
            Method: post
  StreamFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: trigged-lambda/
      Handler: app.lambda_handler
      Runtime: python3.12
      Policies:
        - AWSLambdaDynamoDBExecutionRole
      Events:
        DynamoDBStream:
          Type: DynamoDB
          Properties:
            Stream: arn:aws:dynamodb:ap-southeast-2:375065980285:table/user/stream/2026-03-18T08:09:49.899
            StartingPosition: LATEST
            BatchSize: 1

Outputs:
  MyApi:
    Description: API Gateway endpoint URL
      function
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/users"
